In [1]:
import pandas as pd

# Process EPC non-domestic

In [2]:
sample_nd = pd.read_csv("data/epc-nondomestic.csv", nrows=1000)
sample_nd.head()

,certificate_number,address1,address2,address3,posttown,postcode,address,constituency,constituency_label,local_authority,...,building_emissions,aircon_present,aircon_kw_rating,estimated_aircon_kw_rating,ac_inspection_commissioned,building_environment,report_type,primary_energy_value,uprn,uprn_source
0,0000-7404-5801-3694-5935,Rowan House,Hill End Lane,NaN,ST ALBANS,AL4 0RA,"Rowan House, Hill End Lane",E14001507,St Albans,E07000240,...,35.76,No,NaN,NaN,4,Heating and Natural Ventilation,3,221.99,1.000107e+10,Energy Assessor
1,0000-9278-0696-8196-1282,42 George Street,Great Harwood,NaN,BLACKBURN,BB6 7JF,"42 George Street, Great Harwood",E14001299,Hyndburn,E07000120,...,159.05,No,NaN,NaN,4,Heating and Natural Ventilation,3,884.97,1.000104e+11,Energy Assessor
2,0001-2150-4009-1081-1260,251-253 London Road East,Batheaston,NaN,Bath,BA1 7RL,"251-253 London Road East, Batheaston",E14001080,Bath,E06000022,...,69.44,No,NaN,NaN,4,Heating and Natural Ventilation,3,401.12,1.001212e+11,Energy Assessor
3,0001-2823-0043-0321-7174,BLACK HORSE,COVENTRY ROAD,MARTON,CV23 9RH,CV23 9RH,"BLACK HORSE, COVENTRY ROAD, MARTON",E14001309,Kenilworth and Southam,E07000220,...,82.62,No,NaN,NaN,4,Heating and Natural Ventilation,3,614.19,1.001052e+10,Address Matched
4,0001-6857-5728-6832-3157,143 WATER STREET,RADCLIFFE,NaN,RADCLIFFE,M26 3BJ,"143 WATER STREET, RADCLIFFE",E14001145,Bury South,E08000002,...,33.44,No,NaN,NaN,4,Heating and Natural Ventilation,3,193.75,1.000124e+11,Energy Assessor

In [3]:
cols_nd = ["asset_rating_band", 
           "property_type", 
           "lodgement_date",
           "main_heating_fuel",
           "other_fuel_desc",
           "special_energy_uses",
           "renewable_sources",
           "floor_area",
           "asset_rating",
           "inspection_date",
           "standard_emissions",
           "target_emissions",
           "typical_emissions",
           "building_emissions",
           "aircon_present",
           "lodgement_datetime",
           "primary_energy_value",
           "building_level",
           "ac_inspection_commissioned",
           "building_environment",
           "uprn"
           ]
df_nd = pd.read_csv("data/epc-nondomestic.csv", usecols=cols_nd)
df_nd.head()

,asset_rating,asset_rating_band,property_type,inspection_date,lodgement_date,lodgement_datetime,building_level,main_heating_fuel,other_fuel_desc,special_energy_uses,...,floor_area,standard_emissions,target_emissions,typical_emissions,building_emissions,aircon_present,ac_inspection_commissioned,building_environment,primary_energy_value,uprn
0,77,D,Offices and Workshop Businesses,2023-09-19,2023-09-25,2023-09-25 14:34:24,3,Natural Gas,NaN,NaN,...,45,23.15,9.44,37.84,35.76,No,4,Heating and Natural Ventilation,221.99,1.000107e+10
1,58,C,Hotels,2022-09-12,2022-09-16,2022-09-20 19:17:12,3,Natural Gas,NaN,NaN,...,133,136.78,88.90,356.50,159.05,No,4,Heating and Natural Ventilation,884.97,1.000104e+11
2,81,D,B1 Offices and Workshop businesses,2022-03-05,2022-03-05,2022-03-05 07:43:45,3,Natural Gas,NaN,NaN,...,369,42.82,18.01,52.78,69.44,No,4,Heating and Natural Ventilation,401.12,1.001212e+11
3,72,C,Restaurants and Cafes/Drinking Establishments/...,2023-12-12,2024-01-31,2024-01-31 16:42:08,3,Natural Gas,NaN,NaN,...,355,57.27,27.34,109.63,82.62,No,4,Heating and Natural Ventilation,614.19,1.001052e+10
4,66,C,A1/A2 Retail and Financial/Professional services,2020-10-05,2020-10-07,2020-10-07 19:08:45,3,Natural Gas,NaN,NaN,...,579,25.14,13.81,40.46,33.44,No,4,Heating and Natural Ventilation,193.75,1.000124e+11

In [4]:
df_nd.columns = df_nd.columns.str.replace("_", " ")
df_nd.columns = df_nd.columns.str.title()
df_nd.columns = df_nd.columns.str.replace(" ", "")
df_nd.head()

,AssetRating,AssetRatingBand,PropertyType,InspectionDate,LodgementDate,LodgementDatetime,BuildingLevel,MainHeatingFuel,OtherFuelDesc,SpecialEnergyUses,...,FloorArea,StandardEmissions,TargetEmissions,TypicalEmissions,BuildingEmissions,AirconPresent,AcInspectionCommissioned,BuildingEnvironment,PrimaryEnergyValue,Uprn
0,77,D,Offices and Workshop Businesses,2023-09-19,2023-09-25,2023-09-25 14:34:24,3,Natural Gas,NaN,NaN,...,45,23.15,9.44,37.84,35.76,No,4,Heating and Natural Ventilation,221.99,1.000107e+10
1,58,C,Hotels,2022-09-12,2022-09-16,2022-09-20 19:17:12,3,Natural Gas,NaN,NaN,...,133,136.78,88.90,356.50,159.05,No,4,Heating and Natural Ventilation,884.97,1.000104e+11
2,81,D,B1 Offices and Workshop businesses,2022-03-05,2022-03-05,2022-03-05 07:43:45,3,Natural Gas,NaN,NaN,...,369,42.82,18.01,52.78,69.44,No,4,Heating and Natural Ventilation,401.12,1.001212e+11
3,72,C,Restaurants and Cafes/Drinking Establishments/...,2023-12-12,2024-01-31,2024-01-31 16:42:08,3,Natural Gas,NaN,NaN,...,355,57.27,27.34,109.63,82.62,No,4,Heating and Natural Ventilation,614.19,1.001052e+10
4,66,C,A1/A2 Retail and Financial/Professional services,2020-10-05,2020-10-07,2020-10-07 19:08:45,3,Natural Gas,NaN,NaN,...,579,25.14,13.81,40.46,33.44,No,4,Heating and Natural Ventilation,193.75,1.000124e+11

In [5]:
df_nd.describe()

,AssetRating,BuildingLevel,OtherFuelDesc,SpecialEnergyUses,RenewableSources,FloorArea,StandardEmissions,TargetEmissions,TypicalEmissions,BuildingEmissions,AcInspectionCommissioned,PrimaryEnergyValue,Uprn
count,611336.000000,611336.000000,0.0,0.0,0.0,611336.000000,611336.000000,611336.000000,611336.000000,611336.000000,611336.000000,611336.000000,5.576430e+05
mean,66.164240,3.170492,NaN,NaN,NaN,713.747252,39.378533,19.207235,64.006295,49.366525,4.081651,342.725177,5.316612e+10
std,32.797109,0.462761,NaN,NaN,NaN,2945.764573,75.863861,62.764767,195.888820,100.150085,0.434229,687.190559,6.453033e+10
min,-8022.000000,3.000000,NaN,NaN,NaN,2.000000,0.540000,-821.390000,-3285.560000,-5841.920000,1.000000,-41131.200000,2.600000e+01
25%,46.000000,3.000000,NaN,NaN,NaN,88.000000,15.180000,3.080000,13.040000,16.220000,4.000000,146.860000,1.000129e+10
50%,63.000000,3.000000,NaN,NaN,NaN,190.000000,25.300000,9.320000,35.020000,33.080000,4.000000,256.250000,1.009075e+10
75%,83.000000,3.000000,NaN,NaN,NaN,471.000000,50.950000,25.650000,82.972500,63.660000,4.000000,432.150000,1.000521e+11
max,2576.000000,5.000000,NaN,NaN,NaN,423710.000000,27057.700000,36311.300000,106407.000000,48063.000000,5.000000,284303.000000,4.220001e+11

In [6]:
df_nd.info()

<class 'pandas.DataFrame'>
RangeIndex: 611336 entries, 0 to 611335
Data columns (total 21 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   AssetRating               611336 non-null  int64
 1   AssetRatingBand           611336 non-null  str
 2   PropertyType              611336 non-null  str
 3   InspectionDate            611336 non-null  str
 4   LodgementDate             611336 non-null  str
 5   LodgementDatetime         611336 non-null  str
 6   BuildingLevel             611336 non-null  int64
 7   MainHeatingFuel           611336 non-null  str
 8   OtherFuelDesc             0 non-null       float64
 9   SpecialEnergyUses         0 non-null       float64
 10  RenewableSources          0 non-null       float64
 11  FloorArea                 611336 non-null  int64
 12  StandardEmissions         611336 non-null  float64
 13  TargetEmissions           611336 non-null  float64
 14  TypicalEmissions          611336 non-null  float64
 15  BuildingEmissions         611336 non-null  float64
 16  AirconPresent             611336 non-null  str
 17  AcInspectionCommissioned  611336 non-null  int64
 18  BuildingEnvironment       611336 non-null  str
 19  PrimaryEnergyValue        611336 non-null  float64
 20  Uprn                      557643 non-null  float64
dtypes: float64(9), int64(4), str(8)
memory usage: 97.9 MB

In [7]:
df_nd.dtypes

AssetRating                   int64
AssetRatingBand                 str
PropertyType                    str
InspectionDate                  str
LodgementDate                   str
LodgementDatetime               str
BuildingLevel                 int64
MainHeatingFuel                 str
OtherFuelDesc               float64
SpecialEnergyUses           float64
RenewableSources            float64
FloorArea                     int64
StandardEmissions           float64
TargetEmissions             float64
TypicalEmissions            float64
BuildingEmissions           float64
AirconPresent                   str
AcInspectionCommissioned      int64
BuildingEnvironment             str
PrimaryEnergyValue          float64
Uprn                        float64
dtype: object

In [8]:
df_nd[["OtherFuelDesc", "SpecialEnergyUses", "RenewableSources"]] = df_nd[["OtherFuelDesc", "SpecialEnergyUses", "RenewableSources"]].astype(str)
df_nd["Uprn"] = df_nd["Uprn"].astype("Int64")
df_nd.dtypes

AssetRating                   int64
AssetRatingBand                 str
PropertyType                    str
InspectionDate                  str
LodgementDate                   str
LodgementDatetime               str
BuildingLevel                 int64
MainHeatingFuel                 str
OtherFuelDesc                   str
SpecialEnergyUses               str
RenewableSources                str
FloorArea                     int64
StandardEmissions           float64
TargetEmissions             float64
TypicalEmissions            float64
BuildingEmissions           float64
AirconPresent                   str
AcInspectionCommissioned      int64
BuildingEnvironment             str
PrimaryEnergyValue          float64
Uprn                          Int64
dtype: object

## Stats

In [9]:
df_nd.head()

,AssetRating,AssetRatingBand,PropertyType,InspectionDate,LodgementDate,LodgementDatetime,BuildingLevel,MainHeatingFuel,OtherFuelDesc,SpecialEnergyUses,...,FloorArea,StandardEmissions,TargetEmissions,TypicalEmissions,BuildingEmissions,AirconPresent,AcInspectionCommissioned,BuildingEnvironment,PrimaryEnergyValue,Uprn
0,77,D,Offices and Workshop Businesses,2023-09-19,2023-09-25,2023-09-25 14:34:24,3,Natural Gas,NaN,NaN,...,45,23.15,9.44,37.84,35.76,No,4,Heating and Natural Ventilation,221.99,10001072007
1,58,C,Hotels,2022-09-12,2022-09-16,2022-09-20 19:17:12,3,Natural Gas,NaN,NaN,...,133,136.78,88.90,356.50,159.05,No,4,Heating and Natural Ventilation,884.97,100010448217
2,81,D,B1 Offices and Workshop businesses,2022-03-05,2022-03-05,2022-03-05 07:43:45,3,Natural Gas,NaN,NaN,...,369,42.82,18.01,52.78,69.44,No,4,Heating and Natural Ventilation,401.12,100121173581
3,72,C,Restaurants and Cafes/Drinking Establishments/...,2023-12-12,2024-01-31,2024-01-31 16:42:08,3,Natural Gas,NaN,NaN,...,355,57.27,27.34,109.63,82.62,No,4,Heating and Natural Ventilation,614.19,10010523213
4,66,C,A1/A2 Retail and Financial/Professional services,2020-10-05,2020-10-07,2020-10-07 19:08:45,3,Natural Gas,NaN,NaN,...,579,25.14,13.81,40.46,33.44,No,4,Heating and Natural Ventilation,193.75,100012438436

In [10]:
df_nd.describe()

,AssetRating,BuildingLevel,FloorArea,StandardEmissions,TargetEmissions,TypicalEmissions,BuildingEmissions,AcInspectionCommissioned,PrimaryEnergyValue,Uprn
count,611336.000000,611336.000000,611336.000000,611336.000000,611336.000000,611336.000000,611336.000000,611336.000000,611336.000000,557643.0
mean,66.164240,3.170492,713.747252,39.378533,19.207235,64.006295,49.366525,4.081651,342.725177,53166115580.688812
std,32.797109,0.462761,2945.764573,75.863861,62.764767,195.888820,100.150085,0.434229,687.190559,64530334067.53405
min,-8022.000000,3.000000,2.000000,0.540000,-821.390000,-3285.560000,-5841.920000,1.000000,-41131.200000,26.0
25%,46.000000,3.000000,88.000000,15.180000,3.080000,13.040000,16.220000,4.000000,146.860000,10001289587.5
50%,63.000000,3.000000,190.000000,25.300000,9.320000,35.020000,33.080000,4.000000,256.250000,10090749821.0
75%,83.000000,3.000000,471.000000,50.950000,25.650000,82.972500,63.660000,4.000000,432.150000,100052111703.5
max,2576.000000,5.000000,423710.000000,27057.700000,36311.300000,106407.000000,48063.000000,5.000000,284303.000000,422000142689.0

In [11]:
df_nd["PropertyType"].value_counts()

PropertyType
Retail/Financial and Professional Services                                      130928
Offices and Workshop Businesses                                                 103875
A1/A2 Retail and Financial/Professional services                                 74306
B1 Offices and Workshop businesses                                               59160
Restaurants and Cafes/Drinking Establishments/Takeaways                          48208
Storage or Distribution                                                          37536
General Industrial and Special Industrial Groups                                 24468
A3/A4/A5 Restaurant and Cafes/Drinking Establishments and Hot Food takeaways     23783
B8 Storage or Distribution                                                       22035
B2 to B7 General Industrial and Special Industrial Groups                        13717
General Assembly and Leisure, Night Clubs, and Theatres                           8464
Non-residential Institutions: Education                                           6961
Residential Institutions: Hospitals and Care Homes                                6629
Non-residential Institutions: Primary Health Care Building                        6609
Hotels                                                                            6238
Non-residential Institutions: Community/Day Centre                                4647
D1 Non-residential Institutions - Education                                       4540
C2 Residential Institutions - Hospitals and Care Homes                            4117
D2 General Assembly and Leisure plus Night Clubs and Theatres                     3689
D1 Non-residential Institutions - Primary Health Care Building                    3575
C1 Hotels                                                                         3307
D1 Non-residential Institutions - Community/Day Centre                            2398
Residential Institutions: Universities and Colleges                               2253
C2 Residential Institutions - Universities and colleges                           1902
Residential Spaces                                                                1590
Residential spaces                                                                1341
Residential Institutions: Residential Schools                                      896
Non-residential Institutions: Libraries, Museums, and Galleries                    747
C2 Residential Institutions - Residential schools                                  637
Others - Passenger terminals                                                       431
D1 Non-residential Institutions - Libraries Museums and Galleries                  345
Others: Emergency Services                                                         345
Secure Residential Institutions                                                    261
Others: Miscellaneous 24hr Activities                                              240
Others: Stand-Alone Utility Block                                                  210
C2A Secure Residential Institutions                                                192
Others: Passenger Terminals                                                        183
Others - Emergency services                                                        170
Others - Miscellaneous 24hr activities                                             158
Others - Stand alone utility block                                                 118
Non-residential Institutions: Crown and County Courts                               42
Others: Car Parks 24 hrs                                                            31
Others - Car Parks 24 hrs                                                           31
D1 Non-residential Institutions - Crown and County Courts                           23
Name: count, dtype: int64

# Process EPC domestic

In [ ]:
sample_domestic = pd.read_csv("data/epc-domestic.csv", nrows=1000)
sample_domestic.head()

In [ ]:
sample_domestic.dtypes

In [ ]:
sample_domestic.describe()