In [1]:
import pandas as pd

In [2]:
df_nondomestic = pd.read_csv("data/epc-nondomestic.csv")
df_nondomestic.head()

,certificate_number,address1,address2,address3,posttown,postcode,address,constituency,constituency_label,local_authority,...,building_emissions,aircon_present,aircon_kw_rating,estimated_aircon_kw_rating,ac_inspection_commissioned,building_environment,report_type,primary_energy_value,uprn,uprn_source
0,0000-7404-5801-3694-5935,Rowan House,Hill End Lane,NaN,ST ALBANS,AL4 0RA,"Rowan House, Hill End Lane",E14001507,St Albans,E07000240,...,35.76,No,NaN,NaN,4,Heating and Natural Ventilation,3,221.99,1.000107e+10,Energy Assessor
1,0000-9278-0696-8196-1282,42 George Street,Great Harwood,NaN,BLACKBURN,BB6 7JF,"42 George Street, Great Harwood",E14001299,Hyndburn,E07000120,...,159.05,No,NaN,NaN,4,Heating and Natural Ventilation,3,884.97,1.000104e+11,Energy Assessor
2,0001-2150-4009-1081-1260,251-253 London Road East,Batheaston,NaN,Bath,BA1 7RL,"251-253 London Road East, Batheaston",E14001080,Bath,E06000022,...,69.44,No,NaN,NaN,4,Heating and Natural Ventilation,3,401.12,1.001212e+11,Energy Assessor
3,0001-2823-0043-0321-7174,BLACK HORSE,COVENTRY ROAD,MARTON,CV23 9RH,CV23 9RH,"BLACK HORSE, COVENTRY ROAD, MARTON",E14001309,Kenilworth and Southam,E07000220,...,82.62,No,NaN,NaN,4,Heating and Natural Ventilation,3,614.19,1.001052e+10,Address Matched
4,0001-6857-5728-6832-3157,143 WATER STREET,RADCLIFFE,NaN,RADCLIFFE,M26 3BJ,"143 WATER STREET, RADCLIFFE",E14001145,Bury South,E08000002,...,33.44,No,NaN,NaN,4,Heating and Natural Ventilation,3,193.75,1.000124e+11,Energy Assessor

In [3]:
df_nondomestic.columns = df_nondomestic.columns.str.replace("_", " ")
df_nondomestic.columns = df_nondomestic.columns.str.title()
df_nondomestic.columns = df_nondomestic.columns.str.replace(" ", "")
df_nondomestic.head()

,CertificateNumber,Address1,Address2,Address3,Posttown,Postcode,Address,Constituency,ConstituencyLabel,LocalAuthority,...,BuildingEmissions,AirconPresent,AirconKwRating,EstimatedAirconKwRating,AcInspectionCommissioned,BuildingEnvironment,ReportType,PrimaryEnergyValue,Uprn,UprnSource
0,0000-7404-5801-3694-5935,Rowan House,Hill End Lane,NaN,ST ALBANS,AL4 0RA,"Rowan House, Hill End Lane",E14001507,St Albans,E07000240,...,35.76,No,NaN,NaN,4,Heating and Natural Ventilation,3,221.99,1.000107e+10,Energy Assessor
1,0000-9278-0696-8196-1282,42 George Street,Great Harwood,NaN,BLACKBURN,BB6 7JF,"42 George Street, Great Harwood",E14001299,Hyndburn,E07000120,...,159.05,No,NaN,NaN,4,Heating and Natural Ventilation,3,884.97,1.000104e+11,Energy Assessor
2,0001-2150-4009-1081-1260,251-253 London Road East,Batheaston,NaN,Bath,BA1 7RL,"251-253 London Road East, Batheaston",E14001080,Bath,E06000022,...,69.44,No,NaN,NaN,4,Heating and Natural Ventilation,3,401.12,1.001212e+11,Energy Assessor
3,0001-2823-0043-0321-7174,BLACK HORSE,COVENTRY ROAD,MARTON,CV23 9RH,CV23 9RH,"BLACK HORSE, COVENTRY ROAD, MARTON",E14001309,Kenilworth and Southam,E07000220,...,82.62,No,NaN,NaN,4,Heating and Natural Ventilation,3,614.19,1.001052e+10,Address Matched
4,0001-6857-5728-6832-3157,143 WATER STREET,RADCLIFFE,NaN,RADCLIFFE,M26 3BJ,"143 WATER STREET, RADCLIFFE",E14001145,Bury South,E08000002,...,33.44,No,NaN,NaN,4,Heating and Natural Ventilation,3,193.75,1.000124e+11,Energy Assessor

In [4]:
sample_domestic = pd.read_csv("data/epc-domestic.csv", nrows=1000)
sample_domestic.head()

,certificate_number,address1,address2,address3,postcode,posttown,address,constituency,constituency_label,local_authority,...,walls_env_eff,wind_turbine_count,windows_description,windows_energy_eff,windows_env_eff,floor_env_eff,region,country,uprn,uprn_source
0,0000-0467-0622-8297-3123,149 Wilmington Gardens,NaN,NaN,IG11 9TT,BARKING,149 Wilmington Gardens,E14001073,Barking,E09000002,...,Very Poor,0.0,Fully double glazed,Good,Good,NaN,E12000007,England,1.000510e+08,Energy Assessor
1,0000-1023-0922-4029-3103,118 BRUDENELL ROAD,HYDE PARK,NaN,LS6 1LS,LEEDS,"118 BRUDENELL ROAD, HYDE PARK",E14001319,Leeds Central and Headingley,E08000035,...,Poor,0.0,Fully double glazed,Average,Average,NaN,E12000003,England,7.203190e+07,Energy Assessor
2,0000-1051-0332-5101-3853,1602,2 William Jessop Way,NaN,L3 1EY,Liverpool,"1602, 2 William Jessop Way",E14001338,Liverpool Riverside,E08000012,...,Average,0.0,High performance glazing,Very Good,Very Good,NaN,E12000002,England,3.835019e+07,Address Matched
3,0000-1116-0432-2492-3343,44 Bromford Road,NaN,NaN,B69 4BH,OLDBURY,44 Bromford Road,E14001574,West Bromwich,E08000028,...,Very Good,0.0,High performance glazing,Very Good,Very Good,NaN,E12000005,England,1.009617e+10,Energy Assessor
4,0000-1154-0622-0107-3853,26 Melrose Avenue Woodfield,Road Sparkbrook,NaN,B12 8UH,Birmingham,"26 Melrose Avenue Woodfield, Road Sparkbrook",E14001094,Birmingham Hall Green and Moseley,E08000025,...,Very Poor,0.0,Fully double glazed,Poor,Poor,NaN,E12000005,England,NaN,NaN

In [5]:
sample_domestic.dtypes

certificate_number        str
address1                  str
address2                  str
address3                  str
postcode                  str
                       ...
floor_env_eff             str
region                    str
country                   str
uprn                  float64
uprn_source               str
Length: 93, dtype: object

In [6]:
sample_domestic.describe()

,co2_emiss_curr_per_floor_area,co2_emissions_current,co2_emissions_potential,current_energy_efficiency,energy_consumption_current,energy_consumption_potential,environment_impact_current,environment_impact_potential,extension_count,fixed_lighting_outlets_count,...,number_open_fireplaces,photo_supply,potential_energy_efficiency,report_type,sheating_energy_eff,sheating_env_eff,total_floor_area,unheated_corridor_length,wind_turbine_count,uprn
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,900.000000,1000.00000,...,984.000000,888.000000,1000.000000,1000.00000,0.0,0.0,1000.000000,165.000000,991.000000,9.920000e+02
mean,41.413900,3.300500,1.832300,67.636000,235.479000,135.487000,65.701000,79.620000,0.445556,11.19200,...,0.053862,0.737613,81.483000,2.10000,NaN,NaN,83.762000,5.772976,0.001009,3.113743e+10
std,21.035396,2.348354,1.312093,12.188522,122.945944,85.529592,14.394749,9.661001,0.746018,7.78394,...,0.322354,5.233215,7.654953,0.30015,NaN,NaN,49.956752,2.664578,0.031766,5.372695e+10
min,1.800000,0.200000,-1.300000,1.000000,13.000000,-105.000000,6.000000,26.000000,0.000000,1.00000,...,0.000000,0.000000,16.000000,2.00000,NaN,NaN,13.000000,0.800000,0.000000,3.253600e+04
25%,29.000000,1.875000,1.100000,62.000000,164.750000,88.000000,57.000000,75.000000,0.000000,7.00000,...,0.000000,0.000000,78.000000,2.00000,NaN,NaN,57.000000,4.100000,0.000000,6.309718e+07
50%,38.000000,2.800000,1.600000,69.000000,214.000000,118.000000,67.000000,81.000000,0.000000,10.00000,...,0.000000,0.000000,82.000000,2.00000,NaN,NaN,75.000000,5.580000,0.000000,1.000260e+10
75%,50.000000,4.100000,2.200000,75.000000,281.250000,161.000000,75.000000,85.000000,1.000000,13.00000,...,0.000000,0.000000,86.000000,2.00000,NaN,NaN,96.000000,7.230000,0.000000,1.009606e+10
max,170.000000,31.000000,15.000000,97.000000,1005.000000,650.000000,98.000000,115.000000,4.000000,100.00000,...,6.000000,60.000000,116.000000,3.00000,NaN,NaN,661.000000,15.270000,1.000000,4.220001e+11